# Generated by Django 5.2.16 on 2026-07-20 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('max_attempts', models.PositiveSmallIntegerField(default=1)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('pass_mark', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('randomize_question_order', models.BooleanField(default=False)),
                ('result_release_policy', models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled'), ('manual', 'Manual')], default='immediate', max_length=16)),
                ('explanation_release_policy', models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled'), ('manual', 'Manual')], default='immediate', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('closed', 'Closed'), ('evaluated', 'Evaluated'), ('released', 'Released'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assessments', to=settings.AUTH_USER_MODEL)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='core.cohort')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_datetime', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('evaluated', 'Evaluated'), ('cancelled', 'Cancelled')], default='in_progress', max_length=16)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('assessment', 'student', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('statement', models.TextField()),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('numerical', 'Numerical'), ('short_answer', 'Short Answer'), ('coding', 'Coding')], max_length=32)),
                ('topic', models.CharField(blank=True, max_length=128)),
                ('subtopic', models.CharField(blank=True, max_length=128)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=16)),
                ('positive_marks', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('default_time_minutes', models.PositiveSmallIntegerField(default=5)),
                ('explanation', models.TextField(blank=True)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('visible', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_format', models.TextField(blank=True)),
                ('output_format', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('supported_languages', models.JSONField(blank=True, default=list)),
                ('time_limit_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('memory_limit_mb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_questions', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodingTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('points', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_test_cases', to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('marks', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='core.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_links', to='core.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('assessment', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_answer', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('text_answer', models.TextField(blank=True)),
                ('code_answer', models.TextField(blank=True)),
                ('awarded_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.assessmentquestion')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.attempt')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.choice')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='selected_in_answers', to='core.choice')),
            ],
            options={
                'unique_together': {('attempt', 'assessment_question')},
            },
        ),
    ]
