# Generated by Django 5.2.16 on 2026-07-22 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assessment_attempt_question_codingtestcase_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='explanation_release_at',
            field=models.DateTimeField(blank=True, help_text='Used when explanation release policy is "scheduled".', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='result_release_at',
            field=models.DateTimeField(blank=True, help_text='Used when result release policy is "scheduled".', null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='publishing_coordinators',
            field=models.ManyToManyField(blank=True, help_text='Student coordinators explicitly granted permission to publish assessments for this cohort.', related_name='publishing_cohorts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_numeric_answer',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Exact expected value for numerical-answer questions.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_text_answer',
            field=models.CharField(blank=True, help_text='Expected text for short-answer questions (case-insensitive exact match).', max_length=512),
        ),
    ]
